### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by KyGao** [juditacs/subword-choice#1]
Thanks for sharing the great work! I was wondering if there is an expected date on when you will be releasing your code.

**Comment by juditacs** [comment]
Thanks for the inquiry. I'm close to finishing it. I'll try to release it next week as time allows. Detailed documentation might have to wait a bit more.

**Comment by juditacs** [comment]
I released the code in another repository, the configs are here though. I'll soon add the analysis notebooks. Please read the README for more information.

Please close this issue if you consider it solved.
