### ISSUE TITLE
Layer pooling

### ISSUE THREAD

**Issue by YovaKem** [juditacs/subword-choice#2]
Hi, I'm trying to figure out where in probing/ the config argument `pool_layers ` gets used and what it means exactly. But the only related thing I find is another argument called `layer_pooling` that seems to take on either an Int value like `pool_layers` or a string (e.g. weighted_sum).

Can you clarify the use of these two so I don't mess something when trying to use them? Thanks!

**Comment by juditacs** [comment]
`pool_layers` is the old name of `layer_pooling` and I seem to have forgotten to remove it from the examples. Thank you for pointing it out. I have just removed them https://github.com/juditacs/subword-choice/commit/c149f70d0bdd8f3063ffaacc2049f4d6cdc544b3

Yes, `layer_pooling` is either an integer, the layer you want to use, or one of the following strings: weighted_sum, sum, all, first, last.

**Comment by YovaKem** [comment]
Noted, thanks
